name: GitHub Pages

on:
  push:
    paths-ignore:
      - LICENSE
      - README.md
  pull_request:
    paths-ignore:
      - LICENSE
      - README.md
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Getting own repository
        uses: actions/checkout@v4
        with:
          path: src

      - name: Converts helloworld.md
        working-directory: src
        run: |
          sudo apt update && sudo apt install curl ripgrep jq yq
          mkdir output
          bash gfm2html.sh helloworld.md > output/helloworld.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: src/output

